language: go
go:
  - 1.5

script:
  - go get -v ./...
  - go get -v -t ./...
  - go build -race -o /tmp/dashboard-server server/main/*.go
  - go build -race -o /tmp/dashboard-client client/main/*.go
  - go test ./...
  - npm install
  - bower install
  - karma start
  - gulp lint
  - gulp build
  - make
  - ./test_release.sh ./dasboard-server
  - ./test_release.sh ./dasboard-client
