language: go
go:
  - 1.4

script:
  - go build -race -o /tmp/dashboard-server server/main/*.go
  - go build -race -o /tmp/dashboard-client client/main/*.go
  - go test ./...
  - npm install
  - bower install
  - karma start
  - gulp lint

